### ISSUE TITLE
prefer dexbuilds when building images

### ISSUE THREAD

**Issue by briceburg** [dockerland/dex#49]
Lets prefer fetching dexbuilds images from the dockerhub versus building the source. This will speedup the experience of running an application for this first time. At least 99% of the time...

For this to work, we need to know when the published "dexbuild" is up to date w/ the working copy. One idea is to compare the sha of source tree to a sha published at build time ( could easily modify buildchain for this ), and we'd either host the published shas or see if docker registry supports comparison natively. 

Followup issues can be made for buildchain, and this should be kept in mind for the near rewrite, esp. considering repository organization. Ideally we'd use cop and extend the application configuration to yml in order to deeply express source repositories. For instance, current `sources.list` layout:

```
core git@github.com:dockerland/dex-dockerfiles-core.git
extra git@github.com:dockerland/dex-dockerfiles-extra.git
batools git@github.com:BlueAcornInc/dex-batools.git
```

yaml layout

```yml
---

defaults:
  registry: dockerhub
  endpoint: dockerland

endpoints:
  - name: dockerland
    prefix: https://index.dockerland.org/
    urls:
      dexbuilds: dexbuilds-shasums.gz

# registry is consulted when downloading a "dexbuilds" variant
registries:
  - name: dockerhub
    prefix:
  - name: dockerland
    prefix: registry.dockerland.org/


# and now to the part we had scalar markup for...
sources:
  - name: core
    url: git@github.com:dockerland/dex-dockerfiles-core.git
    registry: dockerland
  - name: extra
    url: git@github.com:dockerland/dex-dockerfiles-extra.git
  - name: batools
    url: git@github.com:BlueAcornInc/dex-batools.git
```
